server.servlet.context-path=/orders
server.port=9021

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=900643
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
my.variable=hello-from-config-server
features.user-tracking-enabled=true

#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
my.variable = order-github-default
